# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vj8_qT5WewY6rjLnFkt2zwlYJ0TM4LU2
"""

import pandas as pd

Teachers = pd.DataFrame({
    "Teacher name": ['Xalilov D.A.', 'Jurayeva G.F.','Raxmatov R.R.','TURDIMATOV M. M.','XONTURAYEV S. I.','ABDULLAYEVA M. R.','QURBONOVA G. M.','DJALILOV M. L.','QADAMOVA Z. E.'],

    "Fanlar": [ 'Suniy intelekt','Elektronika va sxemalar','Kiberxavfsizlik asoslari','Kiberxavfsizlik asoslari','Malumotlar tuzilmasi va algoritmlar','Malumotlar tuzilmasi va algoritmlar','Kompyuterni tashkil etish','Kompyuterni tashkil etish','Suniy intellekt'     ],

    "Fan_turi": [ 'Maruza','Maruza','Amaliy','Maruza','Maruza','Amaliy','Amaliy','Maruza','Amaliy'     ],

    "Yoqadimi ": ['xa','xa','xa','xa','xa','xa','xa','xa','xa'      ],


})
print(Teachers)

Teachers.to_excel('Teachers.xlsx')